package com.yuyuda.mapper;

import com.yuyuda.pojo.SearchRecords;
import java.util.List;

public interface SearchRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int insert(SearchRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    SearchRecords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    List<SearchRecords> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SearchRecords record);
}